### ISSUE TITLE
Running on Windows receive ~/.manifoldrc must be only readable and writable to the current user (0600)")

### ISSUE THREAD

**Issue by briangruber** [manifoldco/manifold-cli#223]
When running the windows version of manifold.exe 0.15.0 I receive the following error
`~/.manifoldrc must be only readable and writable to the current user (0600)")`

Any ideas? Thanks!

**Comment by itsming** [comment]
Hey @briangruber 

@luizbranco is taking a look, thanks for bringing this to our attention. 

cc @enmand

**Comment by briangruber** [comment]
@luizbranco thanks for working on this. Will 0.15.1 be in releases soon? https://releases.manifold.co/manifold-cli/

**Comment by luizbranco** [comment]
Sorry, for the delay. It has been released https://github.com/manifoldco/manifold-cli/releases/tag/v0.15.1

**Comment by briangruber** [comment]
Thanks!
